version: 2

references:
  python_client_image: &python_client_image
    docker:
      - image: circleci/python:3.5

attach_workspace: &attach_workspace
  attach_workspace:
    at: .

jobs:
  setup:
    <<: *python_client_image
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
            - src

  install:
    <<: *python_client_image
    steps:
      - *attach_workspace
      - run:
          name: Install dependencies
          command: make build
  test:
    <<: *python_client_image
    steps:
      - *attach_workspace
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Run unit tests and integration tests
          command: make test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup

      - install:
          requires:
            - setup

      - test:
          requires:
            - install
